apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes/base/namespace.yaml
  - kubernetes/base/deployment.yaml
  - kubernetes/base/ingress.yaml
  - secret.yaml # TODO: SEAL SECRETS 
  - kubernetes/base/service.yaml