apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring # This secret needs to be in the same namespace as Grafana
type: Opaque
stringData:
  adminPassword: "YOUR_STRONG_GRAFANA_PASSWORD" # Replace with a strong password
  adminUser: admin # Default Grafana admin user
