---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: personal-site-infra
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-username/personal-site-infra
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: personal-site
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/clusters/production"
  prune: true
  sourceRef:
    kind: GitRepository
    name: personal-site-infra
  validation: client