apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-blue
  namespace: personal-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-site
      version: blue
  template:
    metadata:
      labels:
        app: personal-site
        version: blue
    spec:
      containers:
      - name: personal-site
        image: ghcr.io/zaneriley/personal-site:v0.3.2-alpha.1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: personal-site-config
        - secretRef:
            name: personal-site-secrets
        env:
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: personal-site-config
              key: POSTGRES_PORT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-green
  namespace: personal-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-site
      version: green
  template:
    metadata:
      labels:
        app: personal-site
        version: green
    spec:
      containers:
      - name: personal-site
        image: ghcr.io/zaneriley/personal-site:v0.3.2-alpha.1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: personal-site-config
        - secretRef:
            name: personal-site-secrets