---
apiVersion: v1
kind: Namespace
metadata:
  name: personal-site

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site
  namespace: personal-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
      - name: personal-site
        image: ghcr.io/zaneriley/personal-site:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: personal-site-secrets
              key: secret-key-base
        - name: DEV_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: personal-site-secrets
              key: dev-token-salt
        - name: PROD_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: personal-site-secrets
              key: prod-token-salt
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: personal-site-secrets
              key: postgres-password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-green
  namespace: personal-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
      - name: personal-site
        image: ghcr.io/zaneriley/personal-site:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: personal-site-secrets
              key: secret-key-base
        - name: DEV_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: personal-site-secrets
              key: dev-token-salt
        - name: PROD_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: personal-site-secrets
              key: prod-token-salt
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: personal-site-secrets
              key: postgres-password

---
apiVersion: v1
kind: Service
metadata:
  name: personal-site-service
  namespace: personal-site
spec:
  selector:
    app: personal-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: personal-site-service-green
  namespace: personal-site
spec:
  containers:
  - name: personal-site
    image: ghcr.io/zaneriley/personal-site:latest  # Update this line
    ports:
    - containerPort: 8000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-site-ingress
  namespace: personal-site
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  tls:
  - hosts:
    - zaneriley.com
    secretName: personal-site-tls
  rules:
  - host: zaneriley.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personal-site-service-blue
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-site-ingress-green
  namespace: personal-site
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  tls:
  - hosts:
    - zaneriley.com
    secretName: personal-site-tls
  rules:
  - host: zaneriley.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personal-site-service-green
            port:
              number: 80
