apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: personal-site-green
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: config
            mountPath: /usr/share/nginx/html
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: config
            configMap:
              name: personal-site-config